### ISSUE TITLE
Primera versión funcional del paquete R

### ISSUE THREAD

**Issue by dieghernan** [dadosdelaplace/Rsubvenciones_spain#5]
Buenas @dadosdelaplace 

Ya hay una primera versión funcional del paquete en el branch [rpak](https://github.com/dadosdelaplace/Rsubvenciones_spain/tree/rpak). Para instalarlo:

```r
require(devtools)
devtools::install_github("dadosdelaplace/Rsubvenciones_spain",
                         ref = "rpak")
```

También se ha generado la documentación online con pkgdown en el branch `gh-pages`, @dadosdelaplace por si quieres publicarla (yo no tengo acceso a los settings).

Algunos puntos a decidir:

## Nombre del paquete

Lo he llamado **subvencionesES** por pura intuición, no tengo ningún problema en cambiarlo.

## Funciones de carga y descarga

He cambiado un poco el funcionamiento. Por defecto guarda una copia local procesada en RData para que las cargas que no sean actualizaciones sean más rápidas. He eliminado la funcionalidad de exportar a csv porque no entendía bien el valor añadido frente a que el usuario lo haga explicitamente, pero se puede comentar. 

En la práctica supone que los parámetros de la versión @dadosdelaplace  y la del paquete han cambiado.

## Funciones adicionales

Según lo que han avanzado los compañeros que funcionan con Python, especialmente @elsatch (https://github.com/JaimeObregon/subvenciones/issues/14) hay funciones para extraer los cifs y para validarlos. Me salían unos 34 CIFs inválidos del total de códigos únicos (casi 900.000), asi que en línea de lo que han visto otros compañeros.

Además hay una función interna para cargar datasets de prueba, esto es sobre todo de cara a usarlo en ejemplos y tests.

## TODO (potencial)

- [ ] Añadir tests al paquete
- [ ] Mejorar el README (en README.Rmd)
- [ ] Crear una viñeta

Saludos
